spring:
  datasource:
    url: jdbc:h2:tcp://localhost:1521/simple-board
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

logging.level:
  org.hibernate.SQL: debug