server:
  port:
    8084

spring:
  profiles:
    default: local

  datasource:
    url: jdbc:h2:tcp://localhost:1521/simple-board
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none
      default_batch_fetch_size: 100

  data:
    web:
      pageable:
        max-page-size: 100
---
spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true

  logging.level:
    org.hibernate.SQL: debug

---
spring:
  config:
    activate:
      on-profile: test

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never